# Generated by Django 4.2.17 on 2025-01-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_remove_userpreference_email_notifications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotification',
        ),
        migrations.RemoveField(
            model_name='joincommunity',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='country_location',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='employment_options',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='english_levels',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='expected_earnings',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='explore_interests',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='job_types',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='team_setups',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='work_locations',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='work_schedules',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='years_experience',
        ),
        migrations.DeleteModel(
            name='EmploymentOption',
        ),
        migrations.DeleteModel(
            name='EnglishLevel',
        ),
        migrations.DeleteModel(
            name='ExpertedEarn',
        ),
        migrations.DeleteModel(
            name='ExploreInterest',
        ),
        migrations.DeleteModel(
            name='JobExperience',
        ),
        migrations.DeleteModel(
            name='JobListType',
        ),
        migrations.DeleteModel(
            name='JoinCommunity',
        ),
        migrations.DeleteModel(
            name='LevelOfEducation',
        ),
        migrations.DeleteModel(
            name='LocationOfWork',
        ),
        migrations.DeleteModel(
            name='TeamSetup',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
        migrations.DeleteModel(
            name='YearsOfExperience',
        ),
    ]
