# Generated by Django 4.2.17 on 2025-01-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkspace', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='teams',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_preferences/images/'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='team',
            field=models.ManyToManyField(related_name='user_teams', to='Teamworkspace.team'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='country_location',
            field=models.ManyToManyField(related_name='user_country_locations', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='employment_options',
            field=models.ManyToManyField(related_name='user_employment_options', to='UserProfile.employmentoption'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='english_levels',
            field=models.ManyToManyField(related_name='user_english_levels', to='UserProfile.englishlevel'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='expected_earnings',
            field=models.ManyToManyField(related_name='user_expected_earnings', to='UserProfile.expertedearn'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='experiences',
            field=models.ManyToManyField(related_name='user_experiences', to='UserProfile.jobexperience'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='explore_interests',
            field=models.ManyToManyField(related_name='user_explore_interests', to='UserProfile.exploreinterest'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='job_types',
            field=models.ManyToManyField(related_name='user_job_types', to='UserProfile.joblisttype'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='languages',
            field=models.ManyToManyField(related_name='user_languages', to='UserProfile.levelofeducation'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='team_setups',
            field=models.ManyToManyField(related_name='user_team_setups', to='UserProfile.teamsetup'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='work_locations',
            field=models.ManyToManyField(related_name='user_work_locations', to='UserProfile.locationofwork'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='work_schedules',
            field=models.ManyToManyField(related_name='user_work_schedules', to='UserProfile.workschedule'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='years_experience',
            field=models.ManyToManyField(related_name='user_years_experience', to='UserProfile.yearsofexperience'),
        ),
    ]
