# Generated by Django 4.2.17 on 2025-01-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_remove_userpreference_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='bio_data',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
