# Generated by Django 4.2.17 on 2025-01-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_userpreference_bio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='bio_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
