# Generated by Django 4.2.17 on 2025-01-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_alter_userpreference_bio_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='max_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='min_salary',
            field=models.IntegerField(default=0),
        ),
    ]
