# Generated by Django 5.1.4 on 2025-01-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_userpreference_max_salary_userpreference_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='email_notifications',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
