# Generated by Django 4.2.17 on 2025-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_userpreference_max_salary_userpreference_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='email_notifications',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
